export {
  HeroSkeleton,
  NavbarSkeleton,
  AboutSkeleton,
  AcademicsSkeleton,
  CurriculumSkeleton,
  HeadteacherSkeleton,
  SchooldriveSkeleton,
  SchoolSlideSkeleton,
  VideoSectionSkeleton,
  NumberCounterSkeleton,
  QuotesSkeleton,
  NewsletterSkeleton,
  FooterSkeleton,
  SigninSkeleton,
  SignupSkeleton,
  DashboardSkeleton,
  ProfileSkeleton,
  default,
} from "./index.jsx";
